site_name: CCM Wiki
nav:
  - Home: index.md
  - Start: start.md
  - Governing: governing.md
  - Scrollsystem: scrollsystem.md
  - Battlesystem: battlesystem.md
  - Blocks: blocks.md
  - Tournaments: tournaments.md
  - Jobs: jobs.md
